services:
  app_postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    command: -p 5433
    ports:
      - "5433:5433"
  app_web:
    build: .
    depends_on:
      - app_postgres
    ports:
      - "8080:8080"