services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "db_simple_app"
      POSTGRES_USER: "user_fael"
      POSTGRES_PASSWORD: "test123"
      PGDATA: "/data/simple-app"       
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  web:
    image: python
    command: sh -c "pip install -r ./app/requirements.txt && python3 ./app/app.py"
    volumes:
      - ./app/:/app/
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - postgres
    ports:
      - "8080:8080"