services:
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  web:
    image: python
    env_file:
      - .env
    command: sh -c "pip install -r ./app/requirements.txt && uvicorn --app-dir=app/ --host ${HOST} --port ${PORT} main:app"
    volumes:
      - ./app/:/app/
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - postgres
    ports:
      - "8080:8080"