-- CREATE TABLE
DROP TABLE IF EXISTS account;
CREATE TABLE account (
    id VARCHAR PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL
);

DROP TABLE IF EXISTS exchange_rate;
CREATE TABLE exchange_rate (
    id VARCHAR PRIMARY KEY,
    symbol VARCHAR NOT NULL,
    amount VARCHAR NOT NULL,
    price VARCHAR NOT NULL,
    type VARCHAR NOT NULL
);